spring:
  application:
    name: altia-eudistack-issuer-enterprise-backend

logging:
  level:
    es.altia: INFO

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always
  tracing:
    sampling:
      probability: 1.0
app:
  data-acquisition:
    sources:
      - credential-configuration-id:
        type:
        endpoint:
        base-dn:
        bind-dn:
        bind-password:
        subject-identifier-attribute:
        mapping:
          first_name:
          family_name:
          email:
          employee_id:
        timeout: 30s
        retry:
          max-attempts: 3
          backoff: 1s
  signing:
    provider:
    coreUrl:
  remote-signature:
    certificate-info-cache-ttl: PT10M
    type:
    url:
    paths:
      sign-path: "/signature/sign"
    client-id:
    client-secret:
    credential-id:
    credential-password:
  issuer-core-backend:
    url: